// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: comments.sql

package schema

import (
	"context"
	"database/sql"
)

const getArticleHeadbyName = `-- name: GetArticleHeadByName :one
select id, name, webhook_url
from article_head_type
where name = $1
`

type GetArticleHeadByNameParams struct {
	Name string `json:"name"`
}

type ArticleHead struct {
	ID         int    `json:"id"`
	IsAdmin    bool   `json:"is_admin"`
	Name       string `json:"name"`
	WebhookURL string `json:"webhook_url"`
}

func (q *Queries) GetArticleHeadByName(ctx context.Context, arg GetArticleHeadByNameParams) (ArticleHead, error) {
	row := q.db.QueryRowContext(ctx, getArticleHeadbyName, arg.Name)
	var i ArticleHead
	var webhookURL sql.NullString
	err := row.Scan(&i.ID, &i.Name, &i.IsAdmin, &webhookURL)
	if webhookURL.Valid {
		i.WebhookURL = webhookURL.String
	} else {
		i.WebhookURL = ""
	}
	return i, err
}

const getArticleHeadList = `-- name: GetArticleHeadList :many
select id, name, is_admin, webhook_url
from article_head_type
order by case 
	when name = '공지' then 0 
	else 1                  
end, name; -- 추가 정렬 (알파벳 순서 등)
`

func (q *Queries) GetArticleHeadList(ctx context.Context) ([]ArticleHead, error) {
	rows, err := q.db.QueryContext(ctx, getArticleHeadList)
	if err != nil {
		return nil, err
	}

	defer rows.Close()
	var items []ArticleHead
	for rows.Next() {
		var i ArticleHead
		var webhookURL sql.NullString
		if err := rows.Scan(&i.ID, &i.Name, &i.IsAdmin, &webhookURL); err != nil {
			return nil, err
		}
		if webhookURL.Valid {
			i.WebhookURL = webhookURL.String
		} else {
			i.WebhookURL = ""
		}
		items = append(items, i)
	}
	return items, nil
}

const getArticleHeadbyID = `-- name: GetArticleHeadByID :one
select id, name, is_admin, webhook_url
from article_head_type
where id = $1
`

type GetArticleHeadByIDParams struct {
	ID int `json:"id"`
}

func (q *Queries) GetArticleHeadByID(ctx context.Context, arg GetArticleHeadByIDParams) (ArticleHead, error) {
	row := q.db.QueryRowContext(ctx, getArticleHeadbyID, arg.ID)
	var i ArticleHead
	var webhookURL sql.NullString
	err := row.Scan(&i.ID, &i.Name, &i.IsAdmin, &webhookURL)
	if webhookURL.Valid {
		i.WebhookURL = webhookURL.String
	} else {
		i.WebhookURL = ""
	}
	return i, err
}

const createArticleHead = `-- name: CreateArticleHead :exec
insert into article_head_type (id, name, webhook_url)
values ($1, $2, $3)
`

func (q *Queries) CreateArticleHead(ctx context.Context, arg ArticleHead) error {
	// check if the article head already exists 
	row, err := q.db.QueryContext(ctx, getArticleHeadbyName, arg.Name)
	if row.Next() {
		return nil
	}

	_, err = q.db.ExecContext(ctx, createArticleHead,
		arg.ID,
		arg.Name,
		arg.WebhookURL,
	)
	return err
}

const updateArticleHead = `-- name: UpdateArticleHead :exec
update article_head_type
set name = $2, is_admin = $3, webhook_url = $4
where id = $1
`

func (q *Queries) UpdateArticleHead(ctx context.Context, arg ArticleHead) error {
	_, err := q.db.ExecContext(ctx, updateArticleHead,
		arg.ID,
		arg.Name,
		arg.IsAdmin,
		arg.WebhookURL,
	)
	return err
}

const deleteArticleHead = `-- name: DeleteArticleHead :exec
delete from article_head_type
where id = $1
`

type DeleteArticleHeadParams struct {
	ID int `json:"id"`
}

func (q *Queries) DeleteArticleHead(ctx context.Context, arg DeleteArticleHeadParams) error {
	_, err := q.db.ExecContext(ctx, deleteArticleHead, arg.ID)
	return err
}
